name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "scripts/**"
      - "src/**"
      - "tests/**"
      - "README.md"
      - ".dockerignore"
      - "pyproject.toml"
      - "uv.lock"
      - "Dockerfile"
  push:
    branches-ignore:
      - main
    paths:
      - ".github/workflows/**"
      - "scripts/**"
      - "src/**"
      - "tests/**"
      - "README.md"
      - ".dockerignore"
      - "pyproject.toml"
      - "uv.lock"
      - "Dockerfile"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/_checks.yml
